#!/usr/bin/env bash
#file transfer

#variables
file="$1"
ip="$2"
user="ubuntu"
key="~/.ssh/id_rsa"


if [$# -lt 4]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
